services:
  postgres:
    image: postgres:15-alpine
    container_name: forever_stack_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - forever_stack_network
    restart: unless-stopped
    env_file: .env

  nextjs:
    env_file: .env
    build:
      context: ./nextjs/app
      dockerfile: Dockerfile
    container_name: forever_stack_nextjs
    ports:
      - "3000:3000"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  perl:
    env_file: .env
    build:
      context: ./perl
      dockerfile: Dockerfile
    container_name: forever_stack_perl
    ports:
      - "5000:5000"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  php:
    env_file: .env
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: forever_stack_php
    ports:
      - "8000:8000"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  java:
    env_file: .env
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: forever_stack_java
    ports:
      - "8080:8080"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  go:
    env_file: .env
    build:
      context: ./go
      dockerfile: Dockerfile
    container_name: forever_stack_go
    ports:
      - "8081:8081"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  ruby:
    env_file: .env
    build:
      context: ./ruby
      dockerfile: Dockerfile
    container_name: forever_stack_ruby
    ports:
      - "3001:3001"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  python:
    env_file: .env
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: forever_stack_python
    ports:
      - "8002:8000"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  coldfusion:
    env_file: .env
    build:
      context: ./coldfusion
      dockerfile: Dockerfile
    container_name: forever_stack_coldfusion
    ports:
      - "8854:8888"
      - "8054:80"
    networks:
      - forever_stack_network
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    env_file: .env
    image: nginx:alpine
    container_name: forever_stack_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - forever_stack_network
    depends_on:
      - nextjs
      - perl
      - php
      - java
      - go
      - ruby
      - python
      - coldfusion
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  forever_stack_network:
    driver: bridge
